### ISSUE TITLE
您好，https://github.com/rainzhop/hdc-devcloud-game-mask-ch1 我最近在学习您的口罩配送大作战的算法，可是华为把您的帖子屏蔽了，看不到，您方便重新分享一下吗？万分感激[可怜]

### ISSUE THREAD

**Issue by ZHANGDINGREN123** [rainzhop/hdc-devcloud-game-mask-ch1#1]
您好，https://github.com/rainzhop/hdc-devcloud-game-mask-ch1
我最近在学习您的口罩配送大作战的算法，可是华为把您的帖子屏蔽了，看不到，您方便重新分享一下吗？万分感激[可怜]

**Comment by rainzhop** [comment]
> 您好，https://github.com/rainzhop/hdc-devcloud-game-mask-ch1
> 我最近在学习您的口罩配送大作战的算法，可是华为把您的帖子屏蔽了，看不到，您方便重新分享一下吗？万分感激[可怜]

您好，已更新思路分享，感谢您的关注🙂
